### ISSUE TITLE
Topics to include 

### ISSUE THREAD

**Issue by trungams** [Compete-McGill/bees#1]
@Compete-McGill/bees 
This is just to keep track of everything we want to include in the reference document. Comment if you want to add/remove anything.

- General:
    - [ ] template.cpp
    - [ ] .vimrc
    - [ ] .bashrc
    - [ ] Makefile
- Data Structures:
    - [ ] Min/Max Stack/Queue
    - [ ] Union Find Disjoint Set
    - [ ] Fenwick Tree
    - [ ] Segment Tree
    - [ ] Treap
- Number Theory:
    - [ ] Modular Arithmetic
    - [ ] Primality
    - [ ] Divisibility
    - [ ] Fractions
- Combinatorics:
    - [ ] Binomial Coefficients
- Graphs:
    - [ ] Topological Sorting
    - [ ] Strongly Connected Components
    - [ ] Bridges/Articulation Points
    - [ ] Dijkstra SSSP
    - [ ] Bellman-Ford Shortest Paths with Negative Weights
    - [ ] Floyd-Warshall APSP
    - [ ] Eulerian Path
    - [ ] Edmonds-Karps Maximum Flow
    - [ ] Dinic's Maximum Flow
    - [ ] Min Cost Max Flow
    - [ ] Graph Matching
- Trees
    - [ ] Minimum Spanning Tree
    - [ ] Lowest Common Ancestor
- Geometry:
    - [ ] Basics
    - [ ] Convex Hull
- Strings:
    - [ ] String Hashing
    - [ ] Prefix Function, KMP
    - [ ] Z Function
    - [ ] Tries
    - [ ] Aho-Corasick
    - [ ] Suffix Tree
    - [ ] Manacher's Algorithm
- Numerical:
- Misc:
    - [ ] Longest Increasing Subsequence
    - [ ] Postfix Calculator
    - [ ] Gaussian Elimination
    - [ ] Binary Search
    - [ ] Ternary Search
